// Builds the static site into dist/:
//   - copies index.html and app/
//   - writes config.js from environment variables (public values only)
//
//   SUPABASE_URL=... SUPABASE_ANON_KEY=... node scripts/build.mjs
//   DEMO_MODE=history node scripts/build.mjs   (preview without a database)
//
// Locally, a .env file is read if present. Without the variables the site
// still builds and runs as the original dashboard (or ?demo=1).
import { cpSync, mkdirSync, rmSync, writeFileSync, readFileSync, existsSync } from "node:fs";

const root = new URL("..", import.meta.url).pathname;
if (existsSync(root + ".env")) {
  for (const line of readFileSync(root + ".env", "utf8").split("\n")) {
    const m = /^\s*([A-Z0-9_]+)\s*=\s*(.*?)\s*$/.exec(line);
    if (m && !(m[1] in process.env)) process.env[m[1]] = m[2].replace(/^["']|["']$/g, "");
  }
}
const url = process.env.SUPABASE_URL || "";
// Optional preview without a database: DEMO_MODE=sample or DEMO_MODE=history.
const demoMode = ["sample", "history"].includes(process.env.DEMO_MODE) ? process.env.DEMO_MODE : null;
const anon = process.env.SUPABASE_ANON_KEY || "";

// Refuse to publish a service-role key by mistake: it would bypass every
// security rule. Supabase keys are JWTs whose payload names the role.
function roleOf(key) {
  try { return JSON.parse(Buffer.from(key.split(".")[1], "base64url").toString()).role; } catch { return null; }
}
if (anon && (roleOf(anon) === "service_role" || anon.startsWith("sb_secret_"))) {
  console.error("SUPABASE_ANON_KEY is a service-role/secret key. Use the anon (public) key instead. Build stopped.");
  process.exit(1);
}
if (url && !/^https:\/\/[a-z0-9-]+\.supabase\.(co|in)\/?$/.test(url) && !process.env.ALLOW_CUSTOM_SUPABASE_URL) {
  console.warn(`Note: SUPABASE_URL (${url}) doesn't look like https://<project>.supabase.co`);
}

const out = root + "dist/";
rmSync(out, { recursive: true, force: true });
mkdirSync(out);
cpSync(root + "index.html", out + "index.html");
cpSync(root + "app", out + "app", { recursive: true });
const config = url && anon ? { supabaseUrl: url.replace(/\/$/, ""), supabaseAnonKey: anon } : demoMode ? { demo: demoMode } : null;
writeFileSync(out + "config.js",
  "// Generated by scripts/build.mjs. Public values only (the anon key is safe to expose; RLS protects the data).\n" +
  (config ? `window.LOCKEDIN_CONFIG = ${JSON.stringify(config)};\n` : "// No Supabase configured: the original dashboard runs on its own.\n"));
console.log(`Built dist/ (${config?.supabaseUrl ? "Supabase mode: " + config.supabaseUrl : config ? "preview: " + config.demo : "no database configured"})`);
